/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package writers;

import java.io.BufferedWriter;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.Writer;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author matheus
 */
public class WriteFile {
    
    public static Writer writer = null;
    
    public WriteFile(String pathname, String content) {
    
        

        try {
            writer = new BufferedWriter(new OutputStreamWriter(
                  new FileOutputStream(pathname), "utf-8"));
            
            writer.write("# Generated by GSDE Circuit at " + Calendar.getInstance().getTime() + "\n");
            writer.write(content);
            
            writer.close();
        } catch (IOException ex) {
        } finally {
           try {writer.close();} catch (Exception ex) {/*ignore*/}
        }
    }
    
    public WriteFile(String pathname) {
            
        try {
            writer = new BufferedWriter(new OutputStreamWriter(
                  new FileOutputStream(pathname), "utf-8"));            
            writer.write("# Generated by GSDE Circuit at " + Calendar.getInstance().getTime() + "\n");            
        } catch (IOException ex) {
        }
    }
    
    public static void WriteContent(String content) {
        try {
            writer.write(content);
        } catch (IOException ex) {
            Logger.getLogger(WriteFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void CloseFile() {
        try {
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(WriteFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
