/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package writers;

import java.io.*;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author matheus
 */
public class WriteFile {
    
    public static Writer writer = null;
    

    public WriteFile(String pathname, String content) {
        try {
            writer = new BufferedWriter(new OutputStreamWriter(
                  new FileOutputStream(pathname), "utf-8"));
            
            writer.write("# Generated by GSDE Circuit at " + Calendar.getInstance().getTime() + "\n");
            writer.write(content);
            
            writer.close();
        } catch (IOException ex) {
        } finally {
           try {writer.close();} catch (Exception ex) {/*ignore*/}
        }
    }
    
    public WriteFile(String pathname) {
            
        try {
            writer = new BufferedWriter(new OutputStreamWriter(
                  new FileOutputStream(pathname), "utf-8"));            
            writer.write("# Generated by GSDE Circuit at " + Calendar.getInstance().getTime() + "\n");            
        } catch (IOException ex) {
        }
    }

    /***
     * @author: Clayton
     * Create file with certain extension
     * @param pathname
     * @param content
     */
    public WriteFile(String pathname, ArrayList <String> content, String extension){
        try {
            FileWriter myWriter = new FileWriter(pathname + extension);
            for (int i = 0; i < content.size(); i++) {
                myWriter.write(content.get(i) + "\n");
            }
            myWriter.close();
            System.out.println("- Successfully wrote file: " + pathname + extension);
        } catch (IOException e) {
            System.err.println("- Error found writing file: " + pathname + extension);
            e.printStackTrace();
        }
    }
    
    public static void WriteContent(String content) {
        try {
            writer.write(content);
        } catch (IOException ex) {
            Logger.getLogger(WriteFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void CloseFile() {
        try {
            writer.close();
        } catch (IOException ex) {
            Logger.getLogger(WriteFile.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
