//
// Generated by GSDE Circuit at Sun Oct 28 15:29:45 BRT 2018
//

module c20_cadence (
    G1gat, G2gat, G3gat, G4gat, G5gat, G6gat, G7gat, G8gat, G9gat, G10gat, 
    G11gat, G12gat, G13gat, G14gat, G15gat, G16gat, G17gat);
  input G1gat, G2gat, G3gat, G4gat, G5gat, G6gat, G7gat, G8gat, G9gat, G10gat, 
    G11gat, G12gat, G13gat, G14gat, G15gat, G16gat;
  output G17gat;
  wire w1, w2, w3, w4, w5, w6, w7, w8, w9, w10, 
    w11, w12, w13, w14, w15, w16, w17, w18, w19, w16_1, 
    w13_3, w13_2, w13_1, w14_2, w14_1, w10_3, w10_2, w10_1, w11_2, w11_1, 
    w3_3, w3_2, w3_1, w4_3, w4_2, w4_1, w5_2, w5_1, w6_2, w6_1, 
    w7_2, w7_1;
  AND2X1   G000(.A(G1gat), .B(G2gat), .Y(w1));
  OR2X1    G001(.A(G4gat), .B(G5gat), .Y(w2));
  NAND2X1  G005(.A(G6gat), .B(G7gat), .Y(w3));
  AND2X1   G002(.A(G8gat), .B(G9gat), .Y(w4));
  OR2X1    G007(.A(G10gat), .B(G11gat), .Y(w5));
  AND2X1   G008(.A(G12gat), .B(G13gat), .Y(w6));
  NAND2X1  G003(.A(G14gat), .B(G15gat), .Y(w7));
  INVX1    G009(.A(G16gat), .Y(w8));
  OR2X1    G004(.A(G3gat), .B(w2), .Y(w9));
  INVX1    G006(.A(w4), .Y(w10));
  NAND3X1  G010(.A(w5), .B(w6), .C(w7), .Y(w11));
  AND2X1   G012(.A(w1), .B(w9), .Y(w12));
  OR2X1    G011(.A(w3), .B(w10), .Y(w13));
  INVX1    G014(.A(w11), .Y(w14));
  INVX1    G013(.A(w13), .Y(w15));
  XOR2X1   G016(.A(w14), .B(w13_1), .Y(w16));
  NOR3X1   G018(.A(w8), .B(w13_2), .C(w14_1), .Y(w17));
  AND2X1   G015(.A(w12), .B(w15), .Y(w18));
  NAND2X1  G017(.A(w18), .B(w16), .Y(w19));
  OR3X1    G019(.A(w19), .B(w17), .C(w16_1), .Y(G17gat));
  XOR2X1   G016_1(.A(w13_3), .B(w14_2), .Y(w16_1));
  OR2X1    G011_3(.A(w10_1), .B(w3_1), .Y(w13_3));
  OR2X1    G011_2(.A(w10_2), .B(w3_2), .Y(w13_2));
  OR2X1    G011_1(.A(w10_3), .B(w3_3), .Y(w13_1));
  INVX1    G014_2(.A(w11_1), .Y(w14_2));
  INVX1    G014_1(.A(w11_2), .Y(w14_1));
  INVX1    G006_3(.A(w4_1), .Y(w10_3));
  INVX1    G006_2(.A(w4_2), .Y(w10_2));
  INVX1    G006_1(.A(w4_3), .Y(w10_1));
  NAND3X1  G010_2(.A(w5_1), .B(w6_1), .C(w7_1), .Y(w11_2));
  NAND3X1  G010_1(.A(w5_2), .B(w6_2), .C(w7_2), .Y(w11_1));
  NAND2X1  G005_3(.A(G6gat), .B(G7gat), .Y(w3_3));
  NAND2X1  G005_2(.A(G6gat), .B(G7gat), .Y(w3_2));
  NAND2X1  G005_1(.A(G6gat), .B(G7gat), .Y(w3_1));
  AND2X1   G002_3(.A(G8gat), .B(G9gat), .Y(w4_3));
  AND2X1   G002_2(.A(G8gat), .B(G9gat), .Y(w4_2));
  AND2X1   G002_1(.A(G8gat), .B(G9gat), .Y(w4_1));
  OR2X1    G007_2(.A(G10gat), .B(G11gat), .Y(w5_2));
  OR2X1    G007_1(.A(G10gat), .B(G11gat), .Y(w5_1));
  AND2X1   G008_2(.A(G12gat), .B(G13gat), .Y(w6_2));
  AND2X1   G008_1(.A(G12gat), .B(G13gat), .Y(w6_1));
  NAND2X1  G003_2(.A(G14gat), .B(G15gat), .Y(w7_2));
  NAND2X1  G003_1(.A(G14gat), .B(G15gat), .Y(w7_1));
endmodule